[package]
name = "inkkeep-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "inkkeep"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
inkkeep-core = { path = "../inkkeep-core" }
inkkeep-win = { path = "../inkkeep-win" }
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-global-shortcut = "2"
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
toml = "0.8"
tauri-plugin-notification = "2"
